security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            mongodb:
                class: App\Document\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                success_handler: App\Security\RoleBasedRedirectHandler
                enable_csrf: true
            logout:
                path: /logout
                target: app_login

    access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/hr, roles: ROLE_HR }
    - { path: ^/developer, roles: ROLE_DEVELOPER }

