version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: hrm_portal-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mongodb

  nginx:
    image: nginx:alpine
    container_name: hrm_portal-nginx
    ports:  
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mongodb:
    image: mongo:6
    container_name: hrm_portal-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db:rw

  mailer:
    image: axllent/mailpit
    container_name: hrm_portal-mailer
    ports:
      - "62953:1025"
      - "62954:8025"

volumes:
  mongodb_data:
